import fs from "fs";
import { lch, rgb } from "d3-color";

try {
  const params = JSON.parse(fs.readFileSync("./epub/params.json", "utf8"));
  const { edition } = params?.params?.metadata;

  if (edition) {
    const color = lch(rgb("#a16e1b")); //50.45, 52.5, 75.43);

    const base = hashCode("beletrie") - hashCode(edition);
    color.h += base;

    fs.writeFileSync(
      "./assets/style/_accent.scss",
      writeCss(color.formatRgb(), color.brighter(1.2).formatRgb())
    );
  }
} catch {}

function hashCode(string) {
  let hash = 0,
    i,
    chr;
  if (string.length === 0) return hash;
  for (i = 0; i < string.length; i++) {
    chr = string.charCodeAt(i);
    hash = (hash << 5) - hash + chr;
    hash |= 0; // Convert to 32bit integer
  }
  return hash;
}

function writeCss(color, brighter) {
  const comment = `// generated by "npm run calc-accent"`;
  const code = `body {
      --title-color: ${color};
      --accent-color: ${color};

      @media (prefers-color-scheme: dark) {
        --title-color: ${color};
        --accent-color: ${brighter};
      }

      &.nb-color-scheme-light {
        --title-color: ${color};
        --accent-color: ${color};
      }

      &.nb-color-scheme-dark {
        --title-color: ${color};
        --accent-color: ${brighter};
      }
    }`;
  return `${comment}\n\n${code}`;
}
